disabled docs in .github stuff

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -93,30 +93,30 @@ jobs:
           nimble test
           echo "=========================="
 
-      - name: Build docs
-        if: ${{ matrix.docs }} == 'true'
-        shell: bash
-        run: |
-          cd project
-          branch=${{ github.ref }}
-          branch=${branch##*/}
-          nimble doc --project --outdir:docs --path="." \
-            '--git.url:https://github.com/${{ github.repository }}' \
-            '--git.commit:${{ github.sha }}' \
-            "--git.devel:$branch" \
-            actors.nim
-          # Ignore failures for older Nim
-          cp docs/{the,}index.html || true
-
-      - name: Publish docs
-        if: >
-          github.event_name == 'push' && github.ref == 'refs/heads/master' &&
-          matrix.os == 'macos-latest' && matrix.nim == 'devel'
-        uses: crazy-max/ghaction-github-pages@v3.1.0
-        with:
-          build_dir: project/docs
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          #        - name: Build docs
+          #          if: ${{ matrix.docs }} == 'true'
+          #          shell: bash
+          #          run: |
+          #            cd project
+          #            branch=${{ github.ref }}
+          #            branch=${branch##*/}
+          #            nimble doc --project --outdir:docs --path="." \
+          #              '--git.url:https://github.com/${{ github.repository }}' \
+          #              '--git.commit:${{ github.sha }}' \
+          #              "--git.devel:$branch" \
+          #              actors.nim
+          #            # Ignore failures for older Nim
+          #            cp docs/{the,}index.html || true
+          #
+          #        - name: Publish docs
+          #          if: >
+          #            github.event_name == 'push' && github.ref == 'refs/heads/master' &&
+          #            matrix.os == 'macos-latest' && matrix.nim == 'devel'
+          #          uses: crazy-max/ghaction-github-pages@v3.1.0
+          #          with:
+          #            build_dir: project/docs
+          #          env:
+          #            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   # Set check-required on this
   success:
